### ISSUE TITLE
panic: unknown field "name" in types.Metadata

### ISSUE THREAD

**Issue by puneet166** [onomyprotocol/onomy#112]
Hi @dzmitryhil  Please help me out regarding this issue ,

When i am trying to run full node using  "./start-onomyd.sh" this script .sh file. 
getting this error. 
![Screenshot from 2022-08-11 15-39-35](https://user-images.githubusercontent.com/48614625/184111984-c2a272c3-f8be-45b5-a4d4-1f2462892800.png)

am i missing something? any dependency?

**Comment by dzmitryhil** [comment]
Check this PR https://github.com/onomyprotocol/onomy/pull/113 @puneet166 
It contnais the updated scripts and share with me the results of the launch please.
