### ISSUE TITLE
Support the `authz` module

### ISSUE THREAD

**Issue by AaronKutch** [onomyprotocol/onomy#135]
somehow, this module was left out, the bridge app has it but not `onomy`

**Comment by AaronKutch** [comment]
also I found that the bridge app doesn't have `feegrant` unlike `onomy`

**Comment by AaronKutch** [comment]
an OIP is required for this, will delay until after everything ONEX related is settled

**Comment by mkaczanowski** [comment]
it would be great to get this rolling :pray:

**Comment by mkaczanowski** [comment]
hi @AaronKutch any updates here? It would be extremely useful to have `authz` module enabled :pray:

**Comment by AaronKutch** [comment]
We have a ONEX testnet to do next week, but I will write an upgrade for it and we will make a proposal when time allows

**Comment by AaronKutch** [comment]
https://github.com/onomyprotocol/onomy/pull/150 will be ready soon

**Comment by AaronKutch** [comment]
@mkaczanowski There has been an update on the testnet just now to include the authz module. Can you test your use case to double check that everything is working as expected?

**Comment by AaronKutch** [comment]
it is in mainnet now
