### ISSUE TITLE
The first height : Error: error during handshake: error on replay: wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by Jackwumingjie** [onomyprotocol/onomy#144]
<img width="865" alt="image" src="https://github.com/onomyprotocol/onomy/assets/39093109/178f6425-b5c1-41fa-b7e9-fae9b369c687">
My node can't run as the picture. And is there the snapshot?

**Comment by Parth4337** [comment]
We started the chain with onomyd version 1.0.0. You are trying to use v1.0.3. You need to start with v1.0.0 and incrementally change/upgrade binary version as needed.

If you dont want to sync the whole chain, You can use state-sync to fast sync your node.
Check out these docs: https://docs.onomy.io/run-a-full-node/starting-a-full-node
